name: Trigger Weekly Newsletter

on:
  # Runs every Sunday at 02:30 UTC (8:00 AM Sunday in India)
  schedule:
    - cron: '30 2 * * 0'
  # Allows manual trigger
  workflow_dispatch:

jobs:
  trigger_newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Call the newsletter trigger endpoint
        run: |
          curl -X POST "${{ secrets.TRIGGER_URL }}?token=${{ secrets.ADMIN_TOKEN }}" -H "Authorization: token ${{ secrets.GH_PAT }}"